[project]
name = "observations-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uuid6>=2025.0.1",
    "uvicorn>=0.35.0",
]
