# Default Parking Monitor Configuration
# Base configuration used as foundation for all environments

# Service Configuration
service:
  name: "com.orangead.parking-monitor"
  port: 9091
  host: "0.0.0.0"
  log_level: "INFO"

# Detection Configuration
detection:
  model_path: "models/yolo11m.pt"
  confidence_threshold: 0.5
  nms_threshold: 0.4
  target_fps: 30.000030  # Precise framerate for macOS USB cameras
  device: "auto"
  batch_size: 1
  
  # Performance optimization
  optimization:
    level: "medium"
    model_caching: true
    frame_caching: true
    gpu_acceleration: true

# Camera Configuration
camera:
  source: 0  # Default camera
  resolution: [1920, 1080]
  fps: 30.000030  # Precise framerate for macOS USB cameras
  buffer_size: 1
  auto_exposure: true
  auto_focus: true

# Parking Zones Configuration
parking_zones:
  auto_detect: true
  total_spaces: 0
  
  # Default zone template
  zones:
    - id: "default"
      name: "Default Zone"
      spaces: 1
      coordinates: [[0, 0], [100, 0], [100, 100], [0, 100]]

# Display Configuration
display:
  enabled: true
  overlay_enabled: true
  overlay_opacity: 0.7
  status_position: "top_right"
  show_vehicle_info: true
  show_fps: false
  show_debug_info: false
  ad_integration: true

# Health Monitoring Configuration
health_monitoring:
  enabled: true
  check_interval: 30
  metrics_retention_hours: 24
  performance_monitoring: true
  auto_recovery: true
  
  thresholds:
    min_fps: 25
    max_memory_gb: 4
    max_cpu_percent: 80
    min_accuracy: 0.9
    max_detection_latency_ms: 100

# Logging Configuration
logging:
  level: "INFO"
  format: "structured"
  max_file_size: "100MB"
  max_files: 5
  console_output: false
  file_output: true
  
  # Log file locations (relative to project root)
  files:
    main: "logs/parking_monitor.log"
    detection: "logs/detection.log"
    performance: "logs/performance.log"
    error: "logs/error.log"

# API Configuration
api:
  enabled: true
  cors_enabled: true
  cors_origins:
    - "http://localhost:*"
    - "http://127.0.0.1:*"
  
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# WebSocket Configuration  
websocket:
  enabled: true
  max_connections: 10
  heartbeat_interval: 30

# Performance Configuration
performance:
  memory_limit_gb: 4
  cpu_limit_percent: 80
  optimization_profile: "balanced"
  
  # Thermal management
  thermal_management:
    enabled: true
    temperature_threshold: 80  # Celsius
    throttle_on_overheat: true

# Integration Configuration
integration:
  dashboard:
    enabled: true
    health_proxy: true
    metrics_export: true
  
  # External services
  services:
    device_api:
      enabled: true
      url: "http://localhost:9090"
    
    player:
      enabled: false
      overlay_integration: false