# oaParkingMonitor Configuration - Clean Pydantic-based System
# This configuration automatically maps to Python objects with validation

# AI Processing Configuration
processing:
  snapshot_interval: 5  # seconds between snapshots
  confidence_threshold: 0.5
  model_path: "models/yolo11m.pt"
  processing_enabled: true

# Camera Hardware Settings
camera:
  # Resolution and frame rate
  width: 1920
  height: 1080
  fps: 30
  
  # Exposure and gain (optimized to fix overexposure)
  exposure: 0.25  # Manual exposure (0-1, -1 for auto)
  gain: 0.3       # Moderate gain
  
  # Image quality parameters
  brightness: 0.4    # Slightly reduced
  contrast: 0.6      # Increased for better definition
  saturation: 0.5    # Normal
  sharpness: 0.6     # Increased for clarity
  white_balance: -1.0  # Auto white balance
  
  # Focus and initialization
  autofocus: true
  warmup_frames: 10
  buffer_size: 1
  mirror: false  # No camera flip

# Image Enhancement Pipeline
enhancement:
  auto_enhance: true
  gamma_correction: 0.8     # Darken overexposed image
  histogram_equalization: false
  clahe_enabled: true       # Enable CLAHE for better contrast
  clahe_clip_limit: 3.0     # Higher for more contrast
  clahe_tile_grid_size: 8

# API Server Settings
api:
  port: 9091
  host: "0.0.0.0"

# Video Input Source
video:
  source: "0"  # Camera device index

# System Configuration
log_level: "INFO"
debug: false

# Parking Zone Definitions (1920x1080 resolution)
parking_zones:
  # A-series: Front row zones - easy detection
  - id: 1
    space_id: 1
    name: "A1"
    description: "Front left"
    coordinates: [[327, 373], [243, 688], [521, 672], [559, 358]]
    detection_difficulty: "easy"
  
  - id: 2
    space_id: 2
    name: "A2"
    description: "Front center-left"
    coordinates: [[559, 358], [521, 672], [791, 662], [785, 346]]
    detection_difficulty: "easy"
  
  - id: 3
    space_id: 3
    name: "A3"
    description: "Front center"
    coordinates: [[785, 346], [791, 662], [1044, 654], [988, 339]]
    detection_difficulty: "easy"
  
  - id: 4
    space_id: 4
    name: "A4"
    description: "Front center-right"
    coordinates: [[988, 339], [1044, 654], [1287, 633], [1194, 330]]
    detection_difficulty: "easy"
  
  - id: 5
    space_id: 5
    name: "A5"
    description: "Front right-center"
    coordinates: [[1194, 330], [1287, 633], [1521, 612], [1411, 320]]
    detection_difficulty: "easy"
  
  - id: 6
    space_id: 6
    name: "A6"
    description: "Front right"
    coordinates: [[1411, 320], [1521, 612], [1770, 602], [1593, 315]]
    detection_difficulty: "easy"
  
  - id: 7
    space_id: 7
    name: "A7"
    description: "Front far right"
    coordinates: [[1593, 315], [1777, 600], [1898, 588], [1899, 452], [1796, 296]]
    detection_difficulty: "easy"
  
  # B-series: Back row zones - hard detection at top edge
  - id: 8
    space_id: 8
    name: "B1"
    description: "Back left"
    coordinates: [[12, 0], [5, 105], [193, 115], [217, 0]]
    detection_difficulty: "hard"
  
  - id: 9
    space_id: 9
    name: "B2"
    description: "Back center-left"
    coordinates: [[217, 0], [193, 115], [391, 96], [399, 0]]
    detection_difficulty: "hard"
  
  - id: 10
    space_id: 10
    name: "B3"
    description: "Back center"
    coordinates: [[399, 0], [391, 96], [583, 79], [573, 0]]
    detection_difficulty: "hard"
  
  - id: 11
    space_id: 11
    name: "B4"
    description: "Back right-center"
    coordinates: [[573, 0], [583, 79], [779, 43], [776, 0]]
    detection_difficulty: "hard"
  
  - id: 12
    space_id: 12
    name: "B5"
    description: "Back right"
    coordinates: [[776, 0], [779, 43], [922, 48], [914, 0]]
    detection_difficulty: "hard"