#!/bin/bash
# Permission Grant Script for oaParkingMonitor
# Helps configure required macOS permissions for parking monitor

echo "[PERMS] Parking Monitor Permission Setup"
echo "========================================"
echo "This script helps configure required permissions for parking monitor"
echo ""
echo "Required Permissions:"
echo "• Camera access for video capture"
echo "• Full disk access for file operations"
echo ""
echo "Manual Configuration Required:"
echo "1. System Preferences → Security & Privacy → Camera"
echo "   → Add parking monitor or Python interpreter"
echo ""
echo "2. System Preferences → Security & Privacy → Full Disk Access"
echo "   → Add parking monitor or Python interpreter"
echo ""
echo "Alternative: Grant permissions via terminal:"
echo "   sudo tccutil reset Camera"
echo "   sudo tccutil reset SystemPolicyAllFiles"
echo ""
echo "[OK] Permission setup guidance complete"
echo "After granting permissions, restart the parking monitor service"